name: GitHub Build Ubuntu Latest
run-name: ${{ github.actor }} build of pkcs11-tools using GitHub Actions
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
    
jobs:

  build-pkcs11-tools-oel-8:

    runs-on: ubuntu-latest
    container:
      image: oraclelinux:8
    steps:
      - name: enable additional repository for autoconf-archive
        run: dnf config-manager --set-enabled ol8_codeready_builder
      - name: install build dependencies
        run:  dnf install openssl-devel git clang autoconf libtool autoconf-archive bison flex make pkg-config perl
      - uses: actions/checkout@v3
      - name: make pkcs11-tools checkout directory acceptable for git
        run:  git config --global --add safe.directory /__w/pkcs11-tools/pkcs11-tools
      - name: make bootstrap.sh executable
        run:  chmod +x bootstrap.sh
      - name: print autoconf version
        run:  autoconf --version && rpm -qi autoconf
      - name: print pkg-config version
        run:  pkg-config --version && rpm -qi pkgconf-pkg-config 
      - name: run bootstrap.sh
        run:  ./bootstrap.sh
      - name: run configure script
        run:  ./configure --prefix=$PWD
      - name: make
        run:  make
      - name: make distribution tar archive
        run:  make dist
      - name: create RPMs
        run:  cp dist/redhat/pkcs11-tools.spec $HOME/rpmbuild/SPECS && 
              cp pkcs11-tools-*.tar.gz $HOME/rpmbuild/SOURCES && 
              rpmbuild -ba $HOME/rpmbuild/SPECS/pkcs11-tools.spec
      - name: list release files
        run:  ls pkcs11-tools-*rpm
      - name: upload pkcs11-tools.rpm to releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name:  pkcs11-tools-latest-oel8-bin.rpm
          files: pkcs11-tools-*rpm

  build-pkcs11-tools-ubuntu-latest:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install build dependencies
        run:  NEEDRESTART_MODE=l sudo apt -y install libssl-dev git clang autoconf libtool autoconf-archive bison flex make pkg-config perl
      - name: make bootstrap.sh executable
        run:  chmod +x bootstrap.sh
      - name: run bootstrap.sh
        run:  ./bootstrap.sh
      - name: run configure script
        run:  ./configure
      - name: make
        run:  make
      - name: make distribution tar archive
        run:  make dist
      - name: list release files
        run:  ls pkcs11-tools-*tar*
      - name: upload pkcs11-tools.tar.gz to releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: pkcs11-tools-ubuntu-latest-bin.tar.gz
          files: pkcs11-tools-*tar*
