name: GitHub Build Ubuntu Latest
run-name: ${{ github.actor }} build of pkcs11-tools using GitHub Actions
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
    
jobs:

  build-pkcs11-tools-ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install build dependencies
        run: NEEDRESTART_MODE=l sudo apt -y install libssl-dev git clang autoconf libtool autoconf-archive bison flex make pkg-config perl
      - name: make bootstrap.sh executable
        run: chmod +x bootstrap.sh
      - name: run bootstrap.sh
        run: ./bootstrap.sh
      - name: run configure script
        run: ./configure
      - name: make
        run: make
      - name: make distribution tar archive
        run: make dist
      - name: upload pkcs11-tools.tar.gz to releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: pkcs11-tools-linux-bin.tar.gz
          files: pkcs11-tools-*tar*
